name: Update raid log
on:
  workflow_dispatch:
    inputs:
      from:
        description: User who is sending the raid
        required: true
      to:
        description: User who is being raided
        required: true

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Update CSV
      run: |
        DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        FROM_USERNAME="$(echo '${{ inputs.from }}' | tr '[:upper:]' '[:lower:]')"
        TO_USERNAME="$(echo '${{ inputs.to }}' | tr '[:upper:]' '[:lower:]')"

        if [[ "$FROM_USERNAME" == "walfas" ]]; then
          FILENAME="public/raids-outgoing.csv"
          OTHER_STREAMER="$TO_USERNAME"
        else
          FILENAME="public/raids-incoming.csv"
          OTHER_STREAMER="$FROM_USERNAME"
        fi

        # Avoid adding duplicate entries for the same day (Sometimes the GitHub
        # Action takes a while to run, and the Twitch webhook will be retried)
        DAY="$(date -u +%Y-%m-%d)"
        if [[ -z $(tail -n 1 $FILENAME | grep "\b$OTHER_STREAMER\b" | grep $DAY) ]]; then
          echo "$DATE,$FROM_USERNAME,$TO_USERNAME" >>$FILENAME

          git add public
          git commit -m "$FROM_USERNAME raided $TO_USERNAME at $DATE"
          git push origin main
        fi

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"

